// Listado maestro de corredores y equipos ciclistas — La Vuelta 2026 (datos reales, 23 equipos / 184 corredores)
// Se usa solo para autocompletar en el panel de admin. No afecta a la puntuación.

const CORREDORES_MAESTRO = [
  "ALBANESE","ALLENO","ALMEIDA","APARICIO","ARCAS",
  "ARMIRAIL","AULAR","AZPARREN","BARTA","BELOKI",
  "BENNETT","BERNARD","BERRADE","BERTHET","BILBAO",
  "BISIAUX","BOUWMAN","BRAET","BRENNAN","BRENNER",
  "BRUSTENGA","BUCHMANN","BUITRAGO","BUSATTO","CALZONI",
  "CAMPRUBI","CANAL","CARAPAZ","CARLOS RODRIGUEZ","CASTRILLO",
  "CHAMBERLAIN","CHRIS HAMILTON","CHUMIL","COBO","COQUARD",
  "CORT","COVI","CRAPS","CRISTIAN RODRIGUEZ","DAINESE",
  "DALBY","DE JONG","DE LA CRUZ","DE PESTEL","DE SCHUYTENEER",
  "DE VYLDER","DEBRUYNE","DIAZ","DOUBLE","DUNBAR",
  "DVERSNES LAVIK","ELOSEGUI","ERMAKOV","FAURA","FEDOROV",
  "FERNANDEZ","FISHER-BLACK","FORTUNATO","GAFFURI","GALL",
  "GARCIA PIERNA","GAROFOLI","GLIVAR","GLOAG","GOGL",
  "GONZALEZ","GOVEKAR","GROVES","HAIG","HAYTER",
  "HELLEMOSE","HERRADA","HIRT","HOFSTETTER","HOULE",
  "JOHANNESSEN","JUAN FELIPE RODRIGUEZ","KAMNA","KIRSCH","KLUCKERS",
  "KONRAD","KRETSCHY","KRON","KRUIJSWIJK","KUNG",
  "KUSS","LABROSSE","LANDA","LANGELLOTTI","LAPORTE",
  "LAURANCE","LE GAC","LEEMREIZE","LEKNESSUND","LUCAS HAMILTON",
  "LUTSENKO","MACIAS","MACKELLAR","MADOUAS","MARTI",
  "MARTIN","MARTINEZ","MAS","MCKENZIE","MEEUS",
  "MIQUEL","MOLARD","MONIQUET","MOSCA","MOSCON",
  "MUHLBERGER","MULUBRHAN","NORDHAGEN","NOVAK","NYS",
  "OLIVEIRA","OMRZEL","ONLEY","OURSELIN","PAASSCHENS",
  "PALENI","PARET-PEINTRE","PEACE","PEDERSEN","PICKERING",
  "POGACAR","PORTER","RAFFERTY","RENARD","RENARD-HAQUIN",
  "RICCITELLO","ROCHAS","ROGLIC","ROMELE","ROMEO",
  "ROOSEN","ROTA","ROULAND","RUIZ","SAMITIER",
  "SCHULTZ","SCOTSON","SENTJENS","SHAW","SIVAKOV",
  "SKJELMOSE","SOSA","STEINHAUSER","SUNEKAER NORSGAARD","SUTTERLIN",
  "SVESTAD-BARDSENG","TARLING","TEJADA","THALMANN","THOMPSON",
  "THORNLEY","TILLER","TJOTTA","TORRES","TRONCHON",
  "TUCKWELL","TULETT","TURNER","UIJTDEBROEKS","URIARTE",
  "VADER","VALTER","VAN AERT","VAN BEKKUM","VAN BOVEN",
  "VAN DEN BOSSCHE","VAN SINTMAARTENSDIJK","VAN TRICHT","VANSEVENANT","VERMAERKE",
  "VERMEERSCH","VINE","WANDAHL","WARBASSE","WEISS",
  "WENZEL","WIDAR","WILKSCH","ZANA"
];

const EQUIPOS_MAESTRO = [
  "ALPECIN","BAHRAIN","DECATHLON","EF",
  "FDJ","INEOS","LIDL-TREK","LOTTO",
  "MOVISTAR","NSN","RED BULL","SOUDAL QUICK STEP",
  "JAYCO ALULA","PICNIC","VISMA","UAE",
  "UNO-X","XDS ASTANA","TUDOR","COFIDIS",
  "Q36.5","BURGOS BH","KERN PHARMA"
];

const PRECIOS_CORREDORES = {
  "DEBRUYNE": 75,
  "GROVES": 300,
  "GOGL": 50,
  "BUSATTO": 50,
  "SENTJENS": 50,
  "DE VYLDER": 50,
  "GLIVAR": 50,
  "HOULE": 50,
  "BILBAO": 125,
  "BUITRAGO": 250,
  "ERMAKOV": 50,
  "MIQUEL": 100,
  "GOVEKAR": 50,
  "OMRZEL": 150,
  "PAASSCHENS": 50,
  "VALTER": 50,
  "BISIAUX": 100,
  "CHAMBERLAIN": 50,
  "DE PESTEL": 50,
  "GALL": 300,
  "LABROSSE": 50,
  "MUHLBERGER": 75,
  "RICCITELLO": 125,
  "SCOTSON": 50,
  "CARAPAZ": 300,
  "SHAW": 50,
  "ALBANESE": 75,
  "BELOKI": 100,
  "MACKELLAR": 50,
  "RAFFERTY": 75,
  "STEINHAUSER": 75,
  "JUAN FELIPE RODRIGUEZ": 50,
  "MARTIN": 150,
  "LE GAC": 50,
  "MOLARD": 50,
  "BERTHET": 100,
  "TRONCHON": 50,
  "PALENI": 50,
  "MADOUAS": 75,
  "ROCHAS": 50,
  "CARLOS RODRIGUEZ": 250,
  "ONLEY": 300,
  "HAIG": 75,
  "LUCAS HAMILTON": 50,
  "LAURANCE": 100,
  "SVESTAD-BARDSENG": 75,
  "TARLING": 100,
  "TURNER": 100,
  "SKJELMOSE": 300,
  "PEDERSEN": 300,
  "NYS": 100,
  "BERNARD": 50,
  "KAMNA": 75,
  "KONRAD": 50,
  "MOSCA": 50,
  "SUNEKAER NORSGAARD": 50,
  "WIDAR": 150,
  "CRAPS": 50,
  "VAN BOVEN": 50,
  "BRAET": 50,
  "DE SCHUYTENEER": 150,
  "ROTA": 75,
  "VAN SINTMAARTENSDIJK": 50,
  "THOMPSON": 50,
  "AULAR": 150,
  "MAS": 250,
  "UIJTDEBROEKS": 200,
  "ROMEO": 200,
  "CANAL": 50,
  "ARCAS": 50,
  "GARCIA PIERNA": 75,
  "CASTRILLO": 100,
  "BENNETT": 75,
  "HIRT": 100,
  "HOFSTETTER": 50,
  "KRETSCHY": 50,
  "LUTSENKO": 50,
  "MARTI": 50,
  "SCHULTZ": 50,
  "VAN TRICHT": 50,
  "ROGLIC": 300,
  "VERMEERSCH": 50,
  "TUCKWELL": 200,
  "FISHER-BLACK": 150,
  "MEEUS": 200,
  "MOSCON": 75,
  "THORNLEY": 50,
  "WANDAHL": 50,
  "VAN DEN BOSSCHE": 50,
  "VANSEVENANT": 50,
  "DAINESE": 200,
  "GAROFOLI": 75,
  "HAYTER": 100,
  "ZANA": 75,
  "LANDA": 125,
  "PARET-PEINTRE": 125,
  "DOUBLE": 75,
  "PICKERING": 50,
  "COVI": 75,
  "HELLEMOSE": 50,
  "SUTTERLIN": 50,
  "MCKENZIE": 50,
  "BOUWMAN": 75,
  "PORTER": 50,
  "MARTINEZ": 50,
  "GAFFURI": 50,
  "CHRIS HAMILTON": 50,
  "RENARD-HAQUIN": 75,
  "DE JONG": 50,
  "LEEMREIZE": 50,
  "PEACE": 50,
  "ROOSEN": 50,
  "VAN AERT": 250,
  "BRENNAN": 300,
  "NORDHAGEN": 125,
  "TULETT": 125,
  "KRUIJSWIJK": 50,
  "LAPORTE": 75,
  "ARMIRAIL": 75,
  "KUSS": 100,
  "POGACAR": 600,
  "ALMEIDA": 300,
  "VINE": 150,
  "SIVAKOV": 100,
  "TORRES": 100,
  "VERMAERKE": 50,
  "OLIVEIRA": 50,
  "NOVAK": 50,
  "JOHANNESSEN": 250,
  "KRON": 75,
  "DVERSNES LAVIK": 50,
  "TILLER": 50,
  "CORT": 75,
  "DALBY": 50,
  "TJOTTA": 50,
  "LEKNESSUND": 75,
  "MULUBRHAN": 100,
  "TEJADA": 100,
  "CRISTIAN RODRIGUEZ": 75,
  "FORTUNATO": 100,
  "LANGELLOTTI": 50,
  "VAN BEKKUM": 50,
  "FEDOROV": 50,
  "ROMELE": 50,
  "BRENNER": 100,
  "KUNG": 75,
  "BARTA": 50,
  "KLUCKERS": 50,
  "THALMANN": 50,
  "WARBASSE": 50,
  "WEISS": 75,
  "WILKSCH": 50,
  "COQUARD": 200,
  "BUCHMANN": 75,
  "RENARD": 50,
  "KIRSCH": 50,
  "MONIQUET": 50,
  "OURSELIN": 75,
  "ROULAND": 50,
  "SAMITIER": 50,
  "CAMPRUBI": 100,
  "CALZONI": 50,
  "DE LA CRUZ": 75,
  "DUNBAR": 125,
  "VADER": 50,
  "GLOAG": 50,
  "AZPARREN": 75,
  "GONZALEZ": 50,
  "HERRADA": 50,
  "DIAZ": 75,
  "CHUMIL": 75,
  "FAURA": 50,
  "APARICIO": 75,
  "FERNANDEZ": 50,
  "ALLENO": 50,
  "MACIAS": 75,
  "COBO": 50,
  "BERRADE": 75,
  "BRUSTENGA": 75,
  "ELOSEGUI": 50,
  "RUIZ": 75,
  "SOSA": 75,
  "URIARTE": 50,
  "WENZEL": 50
};
const PERFILES_ETAPAS = {
  // Perfiles oficiales de cada etapa de La Vuelta 2026 (imágenes vía ciclismoepico.com,
  // originales de A.S.O.). Si en algún momento cambian de sitio o quieres usar otra fuente,
  // solo hay que sustituir estas URLs.
  1: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-01-la-vuelta-2026.webp",
  2: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-02-la-vuelta-2026.webp",
  3: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-03-la-vuelta-2026.webp",
  4: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-04-la-vuelta-2026.webp",
  5: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-05-la-vuelta-2026.webp",
  6: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-06-la-vuelta-2026.webp",
  7: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-07-la-vuelta-2026.webp",
  8: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-08-la-vuelta-2026.webp",
  9: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-09-la-vuelta-2026.webp",
  10: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-10-la-vuelta-2026.webp",
  11: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-11-la-vuelta-2026.webp",
  12: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-12-la-vuelta-2026.webp",
  13: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-13-la-vuelta-2026.webp",
  14: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-14-la-vuelta-2026.webp",
  15: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-15-la-vuelta-2026.webp",
  16: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-16-la-vuelta-2026.webp",
  17: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-17-la-vuelta-2026.webp",
  18: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-18-la-vuelta-2026.webp",
  19: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-19-la-vuelta-2026.webp",
  20: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-20-la-vuelta-2026.webp",
  21: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-21-la-vuelta-2026.webp",
};
