// Listado maestro de corredores y equipos ciclistas (La Vuelta 2026 (PLACEHOLDER: datos reales del Tour, solo para pruebas))
// Se usa solo para autocompletar en el panel de admin. No afecta a la puntuación.

const CORREDORES_MAESTRO = [
"A PARET PEINTRE","ABRAHAMSEN","ACKERMANN","AFFINI","ALAPHILIPPE","ALEX MOLENAAR","ALLEGAERT",
"ANDERS JOHANNESSEN","ARANBURU","ARENSMAN","ARMIRAIL","ARTZ","ASKEY","AYUSO","AZPARREN",
"BALDERSTONE","BALLERINI","BARGUIL","BAUDIN","BAUHAUS","BEN HEALY","BEN THOMAS","BENOOT",
"BERCKMOES","BERNAL","BERWICK","BIERMANS","BIESTERBOS","BITTNER","BRAZ AFONSO","BREUILLARD",
"C BERTHET","CAMPENAERTS","CARAPAZ","CARUSO","CASTRILLO","CATTANEO","CEES BOL","CEPEDA",
"CHARMIG","CHRIS HARPER","CORT NIELSEN","COSTIOU","CRAPS","DE KLEIJN","DE LIE","DEBRUYNE",
"DEGENKOLB","DEL TORO","DELBOVE","DELETTRE","DENZ","DEREK GEE","DHONDT","DILLIER",
"DORIAN GODON","DURBRIDGE","EENKHOORN","ENGELHARDT","EVENEPOEL","FRED WRIGHT","FRETIN","FRIGO",
"G BENNET","G MARTIN","GANNA","GATE","GAVIRIA","GERMANI","GIRMAY","GRADEK","GROSSCHARTNER",
"GUERNALEC","HERMANS","HESSMANN","HIGUITA","HINDLEY","HOOLE","HOWSON","HUGO PAGE","IZAGUIRRE",
"J F PARRA","JAVIER ROMO","JOEL NICOLAU","JORDAN JEGAT","JORGENSON","K ASGREEN","KIRSCH","KOOIJ",
"KUSS","KWIATKOWSKI","LE BERRE","LENNY MTNZ","LIPOWITZ","LOUVEL","LUKE PLAPP","MARC HIRSCHI",
"MARCO HALLER","MARKL","MARSMAN","MATTHEWS","MAX KANTER","MC NULTY","MERLIER","MEURISSE",
"MOHORIC","NEILANDS","O BRIEN","O CONNOR","OLDANI","OLIVEIRA","OTRUBA","PACHER","PEDERSEN",
"PER STRAND HAGENES","PHILIPSEN","PIGANZOLI","PLANCKAERT","PLUIMERS","POGACAR","POLITT",
"PRODHOMME","R GREGOIRE","RAÚL G PIERNA","RICCITELLO","RICKAERT","RUBIO","RUSSO","SCHMID",
"SEAN QUINN","SEIXAS","SIMMONS","SKAARSETH","SKJELMOSE","SKUJINS","SLOCK","STANNARD",
"STEINHAUSER","STEWART","STORER","STUYVEN","TARLING","TEJADA","TEUNISSEN","TIBERI","TOBIAS FOSS",
"TOBIAS JOHANNESSEN","TOM PIDCOCK","TRAEEN","TRATNIK","TRENTIN","TURGIS","UIJTDEBROEKS",
"V PARET PEINTRE","VACEK","VALGREN","VAN ASBROECK","VAN BAARLE","VAN DEN BERG","VAN DEN BROEK",
"VAN DER POEL","VAN DIJKE","VAN EETVELT","VAN GILS","VAN MOER","VAN WILDER","VAUQUELIN",
"VEISTROFFER","VELASCO","VEN LERBERGHE","VEN MECHELEN","VERCHER","VERMEERSCH","VERONA",
"VERSTRYNGE","VERVAEKE","VINGEGAARD","VINOKUROV","WAERENSKJOLD","WALKER","WELLENS",
"YANNIS VOISARD","YATES","ZIMMERMANN"
];

const EQUIPOS_MAESTRO = [
"UAE","ALPECIN","BAHRAIN","DECATHLON","EF","FDJ","INEOS","LIDL-TREK","LOTTO","MOVISTAR",
"NSN","RED BULL","SOUDAL QUICK STEP","JAYCO ALULA","PICNIC","VISMA","UNO-X","XDS ASTANA",
"COFIDIS","TUDOR","TOTAL ENERGIES","CAJA RURAL","PINARELLO"
];
const PRECIOS_CORREDORES = {
  "POGACAR": 650,
  "DEL TORO": 350,
  "WELLENS": 100,
  "MC NULTY": 200,
  "YATES": 200,
  "VERMEERSCH": 75,
  "POLITT": 50,
  "GROSSCHARTNER": 75,
  "PHILIPSEN": 300,
  "VAN DER POEL": 250,
  "VERSTRYNGE": 100,
  "RICKAERT": 50,
  "MARSMAN": 50,
  "DEBRUYNE": 50,
  "PLANCKAERT": 50,
  "DILLIER": 50,
  "TIBERI": 250,
  "LENNY MTNZ": 200,
  "MOHORIC": 75,
  "BAUHAUS": 200,
  "CARUSO": 100,
  "GRADEK": 50,
  "STANNARD": 50,
  "VEN MECHELEN": 50,
  "SEIXAS": 400,
  "KOOIJ": 300,
  "RICCITELLO": 125,
  "BENOOT": 75,
  "HOOLE": 50,
  "PRODHOMME": 75,
  "A PARET PEINTRE": 75,
  "CEES BOL": 75,
  "BEN HEALY": 200,
  "K ASGREEN": 75,
  "CARAPAZ": 250,
  "BAUDIN": 150,
  "SEAN QUINN": 50,
  "STEINHAUSER": 100,
  "WALKER": 50,
  "VALGREN": 75,
  "G MARTIN": 125,
  "R GREGOIRE": 125,
  "C BERTHET": 75,
  "BRAZ AFONSO": 50,
  "GERMANI": 50,
  "PACHER": 50,
  "RUSSO": 50,
  "COSTIOU": 75,
  "ARENSMAN": 300,
  "BERNAL": 250,
  "TOBIAS FOSS": 75,
  "GANNA": 100,
  "DORIAN GODON": 150,
  "KWIATKOWSKI": 75,
  "TARLING": 75,
  "VAUQUELIN": 250,
  "AYUSO": 350,
  "PEDERSEN": 300,
  "VACEK": 150,
  "SKJELMOSE": 250,
  "SIMMONS": 125,
  "DEREK GEE": 250,
  "VERONA": 50,
  "SKUJINS": 50,
  "DE LIE": 200,
  "VAN EETVELT": 100,
  "ZIMMERMANN": 50,
  "ARTZ": 50,
  "BERCKMOES": 50,
  "SLOCK": 75,
  "CRAPS": 50,
  "VEISTROFFER": 50,
  "UIJTDEBROEKS": 200,
  "RAÚL G PIERNA": 75,
  "CASTRILLO": 75,
  "RUBIO": 100,
  "JAVIER ROMO": 100,
  "OLIVEIRA": 50,
  "CEPEDA": 50,
  "HESSMANN": 50,
  "GIRMAY": 300,
  "STEWART": 50,
  "ASKEY": 50,
  "NEILANDS": 50,
  "FRIGO": 75,
  "LOUVEL": 50,
  "G BENNET": 75,
  "VAN ASBROECK": 50,
  "VAN DIJKE": 50,
  "EVENEPOEL": 350,
  "DENZ": 50,
  "LIPOWITZ": 300,
  "CATTANEO": 50,
  "TRATNIK": 50,
  "VAN GILS": 150,
  "HINDLEY": 300,
  "V PARET PEINTRE": 150,
  "MERLIER": 300,
  "EENKHOORN": 50,
  "STUYVEN": 75,
  "VAN BAARLE": 75,
  "VEN LERBERGHE": 50,
  "VAN WILDER": 150,
  "VERVAEKE": 75,
  "MATTHEWS": 100,
  "LUKE PLAPP": 125,
  "ACKERMANN": 100,
  "O CONNOR": 300,
  "SCHMID": 100,
  "O BRIEN": 50,
  "ENGELHARDT": 50,
  "DURBRIDGE": 75,
  "BITTNER": 200,
  "BARGUIL": 50,
  "VAN DEN BROEK": 50,
  "DHONDT": 50,
  "VAN DEN BERG": 50,
  "MARKL": 50,
  "BIESTERBOS": 75,
  "DEGENKOLB": 75,
  "CAMPENAERTS": 75,
  "AFFINI": 50,
  "PER STRAND HAGENES": 50,
  "JORGENSON": 300,
  "KUSS": 125,
  "ARMIRAIL": 75,
  "PIGANZOLI": 200,
  "VINGEGAARD": 450,
  "CORT NIELSEN": 100,
  "TOBIAS JOHANNESSEN": 250,
  "SKAARSETH": 50,
  "WAERENSKJOLD": 150,
  "CHARMIG": 50,
  "ABRAHAMSEN": 50,
  "TRAEEN": 75,
  "ANDERS JOHANNESSEN": 50,
  "TEUNISSEN": 50,
  "HIGUITA": 100,
  "TEJADA": 100,
  "MAX KANTER": 50,
  "VINOKUROV": 50,
  "BALLERINI": 100,
  "GATE": 50,
  "VELASCO": 50,
  "ALLEGAERT": 50,
  "BIERMANS": 75,
  "FRETIN": 100,
  "KIRSCH": 50,
  "HUGO PAGE": 50,
  "ARANBURU": 100,
  "BEN THOMAS": 75,
  "IZAGUIRRE": 75,
  "ALAPHILIPPE": 150,
  "TRENTIN": 100,
  "STORER": 250,
  "PLUIMERS": 75,
  "DE KLEIJN": 100,
  "MARCO HALLER": 50,
  "MARC HIRSCHI": 100,
  "YANNIS VOISARD": 75,
  "JORDAN JEGAT": 75,
  "DELETTRE": 75,
  "TURGIS": 100,
  "VERCHER": 50,
  "LE BERRE": 50,
  "BREUILLARD": 50,
  "DELBOVE": 50,
  "GUERNALEC": 50,
  "ALEX MOLENAAR": 50,
  "JOEL NICOLAU": 50,
  "BALDERSTONE": 75,
  "BERWICK": 75,
  "GAVIRIA": 125,
  "OLDANI": 50,
  "OTRUBA": 50,
  "J F PARRA": 50,
  "TOM PIDCOCK": 200,
  "AZPARREN": 50,
  "CHRIS HARPER": 100,
  "HERMANS": 50,
  "HOWSON": 50,
  "MEURISSE": 50,
  "VAN MOER": 50,
  "FRED WRIGHT": 75
};
const PERFILES_ETAPAS = {
  // Perfiles oficiales de cada etapa de La Vuelta 2026 (imágenes vía ciclismoepico.com,
  // originales de A.S.O.). Si en algún momento cambian de sitio o quieres usar otra fuente,
  // solo hay que sustituir estas URLs.
  1: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-01-la-vuelta-2026.webp",
  2: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-02-la-vuelta-2026.webp",
  3: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-03-la-vuelta-2026.webp",
  4: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-04-la-vuelta-2026.webp",
  5: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-05-la-vuelta-2026.webp",
  6: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-06-la-vuelta-2026.webp",
  7: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-07-la-vuelta-2026.webp",
  8: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-08-la-vuelta-2026.webp",
  9: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-09-la-vuelta-2026.webp",
  10: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-10-la-vuelta-2026.webp",
  11: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-11-la-vuelta-2026.webp",
  12: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-12-la-vuelta-2026.webp",
  13: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-13-la-vuelta-2026.webp",
  14: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-14-la-vuelta-2026.webp",
  15: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-15-la-vuelta-2026.webp",
  16: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-16-la-vuelta-2026.webp",
  17: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-17-la-vuelta-2026.webp",
  18: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-18-la-vuelta-2026.webp",
  19: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-19-la-vuelta-2026.webp",
  20: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-20-la-vuelta-2026.webp",
  21: "https://ciclismoepico.com/wp-content/uploads/2025/11/etapa-21-la-vuelta-2026.webp",
};
